export const citiesArrayConst = [
  // Abruzzo
  { item: "L'Aquila" }, { item: "Pescara" }, { item: "Chieti" }, { item: "Teramo" }, { item: "Montesilvano" }, { item: "Giulianova" }, { item: "Avezzano" }, { item: "Sulmona" }, { item: "Vasto" }, { item: "Lanciano" }, { item: "Ortona" }, { item: "Francavilla al Mare" }, { item: "Roseto degli Abruzzi" }, { item: "Silvi" }, { item: "Pineto" },

  // Basilicata
  { item: "Potenza" }, { item: "Matera" }, { item: "Melfi" }, { item: "Pisticci" }, { item: "Policoro" }, { item: "Lavello" }, { item: "Rionero in Vulture" }, { item: "Bernalda" }, { item: "Montescaglioso" }, { item: "Lauria" }, { item: "Venosa" }, { item: "Nova Siri" }, { item: "Scanzano Jonico" },

  // Calabria
  { item: "Catanzaro" }, { item: "Reggio Calabria" }, { item: "Cosenza" }, { item: "Crotone" }, { item: "Vibo Valentia" }, { item: "Lamezia Terme" }, { item: "Rossano" }, { item: "Corigliano Calabro" }, { item: "Gioia Tauro" }, { item: "Castrovillari" }, { item: "Paola" }, { item: "Siderno" }, { item: "Acri" }, { item: "Rende" }, { item: "Isola di Capo Rizzuto" }, { item: "Villa San Giovanni" }, { item: "Montalto Uffugo" }, { item: "Palmi" },

  // Campania
  { item: "Napoli" }, { item: "Salerno" }, { item: "Caserta" }, { item: "Avellino" }, { item: "Benevento" }, { item: "Giugliano in Campania" }, { item: "Torre del Greco" }, { item: "Pozzuoli" }, { item: "Casoria" }, { item: "Castellammare di Stabia" }, { item: "Afragola" }, { item: "Acerra" }, { item: "Portici" }, { item: "Ercolano" }, { item: "Battipaglia" }, { item: "Scafati" }, { item: "Nocera Inferiore" }, { item: "Marano di Napoli" }, { item: "Cava de' Tirreni" }, { item: "Aversa" }, { item: "Torre Annunziata" }, { item: "Sarno" }, { item: "Casalnuovo di Napoli" }, { item: "Nola" }, { item: "Eboli" }, { item: "Angri" }, { item: "Pagani" }, { item: "Sorrento" }, { item: "Amalfi" }, { item: "Positano" }, { item: "Pompei" }, { item: "Capri" }, { item: "Ischia" },

  // Emilia-Romagna
  { item: "Bologna" }, { item: "Parma" }, { item: "Modena" }, { item: "Reggio Emilia" }, { item: "Ravenna" }, { item: "Rimini" }, { item: "Ferrara" }, { item: "Forlì" }, { item: "Cesena" }, { item: "Piacenza" }, { item: "Imola" }, { item: "Carpi" }, { item: "Faenza" }, { item: "Sassuolo" }, { item: "Riccione" }, { item: "Formigine" }, { item: "Casalecchio di Reno" }, { item: "Cento" }, { item: "Cervia" }, { item: "Fidenza" }, { item: "Cattolica" }, { item: "Comacchio" }, { item: "Cesenatico" }, { item: "Mirandola" }, { item: "Lugo" },

  // Friuli-Venezia Giulia
  { item: "Trieste" }, { item: "Udine" }, { item: "Pordenone" }, { item: "Gorizia" }, { item: "Monfalcone" }, { item: "Sacile" }, { item: "Codroipo" }, { item: "Cordenons" }, { item: "Tolmezzo" }, { item: "Lignano Sabbiadoro" }, { item: "Cividale del Friuli" }, { item: "Gemona del Friuli" }, { item: "Cervignano del Friuli" }, { item: "San Vito al Tagliamento" }, { item: "Gradisca d'Isonzo" },

  // Lazio
  { item: "Roma" }, { item: "Latina" }, { item: "Viterbo" }, { item: "Frosinone" }, { item: "Rieti" }, { item: "Guidonia Montecelio" }, { item: "Fiumicino" }, { item: "Aprilia" }, { item: "Tivoli" }, { item: "Pomezia" }, { item: "Velletri" }, { item: "Civitavecchia" }, { item: "Ardea" }, { item: "Nettuno" }, { item: "Terracina" }, { item: "Gaeta" }, { item: "Formia" }, { item: "Anzio" }, { item: "Cassino" }, { item: "Cisterna di Latina" }, { item: "Monterotondo" }, { item: "Ladispoli" }, { item: "Marino" }, { item: "Bracciano" }, { item: "Albano Laziale" }, { item: "Frascati" }, { item: "Anagni" }, { item: "Ostia" }, { item: "Cerveteri" }, { item: "Fiuggi" }, { item: "Tarquinia" }, { item: "Fondi" }, { item: "Ciampino" }, { item: "Sora" },

  // Liguria
  { item: "Genova" }, { item: "La Spezia" }, { item: "Savona" }, { item: "Imperia" }, { item: "Sanremo" }, { item: "Rapallo" }, { item: "Chiavari" }, { item: "Ventimiglia" }, { item: "Alassio" }, { item: "Sestri Levante" }, { item: "Albenga" }, { item: "Lavagna" }, { item: "Varazze" }, { item: "Santa Margherita Ligure" }, { item: "Bordighera" }, { item: "Finale Ligure" }, { item: "Lerici" }, { item: "Diano Marina" }, { item: "Loano" }, { item: "Arenzano" }, { item: "Portofino" },

  // Lombardia
  { item: "Milano" }, { item: "Brescia" }, { item: "Monza" }, { item: "Bergamo" }, { item: "Como" }, { item: "Varese" }, { item: "Cremona" }, { item: "Pavia" }, { item: "Mantova" }, { item: "Lecco" }, { item: "Lodi" }, { item: "Sondrio" }, { item: "Busto Arsizio" }, { item: "Cinisello Balsamo" }, { item: "Vigevano" }, { item: "Legnano" }, { item: "Gallarate" }, { item: "Rho" }, { item: "Cologno Monzese" }, { item: "Paderno Dugnano" }, { item: "Seregno" }, { item: "Saronno" }, { item: "Desio" }, { item: "Cesano Maderno" }, { item: "Sesto San Giovanni" }, { item: "Voghera" }, { item: "Crema" }, { item: "Gorgonzola" }, { item: "Corsico" }, { item: "Lissone" }, { item: "Cantù" }, { item: "Abbiategrasso" }, { item: "Treviglio" }, { item: "Lumezzane" }, { item: "Meda" }, { item: "Magenta" }, { item: "Cassano d'Adda" }, { item: "Desenzano del Garda" }, { item: "Dalmine" }, { item: "Limbiate" }, { item: "Merate" }, { item: "Bollate" }, { item: "Bresso" }, { item: "Cernusco sul Naviglio" }, { item: "Stradella" }, { item: "Morbegno" }, { item: "Bellagio" },

  // Marche
  { item: "Ancona" }, { item: "Pesaro" }, { item: "Fano" }, { item: "Ascoli Piceno" }, { item: "Macerata" }, { item: "Fermo" }, { item: "Senigallia" }, { item: "Jesi" }, { item: "Civitanova Marche" }, { item: "San Benedetto del Tronto" }, { item: "Fabriano" }, { item: "Porto Sant'Elpidio" }, { item: "Porto San Giorgio" }, { item: "Recanati" }, { item: "Falconara Marittima" }, { item: "Osimo" }, { item: "Urbino" }, { item: "Tolentino" }, { item: "Porto Recanati" }, { item: "Loreto" }, { item: "Camerino" },

  // Molise
  { item: "Campobasso" }, { item: "Isernia" }, { item: "Termoli" }, { item: "Venafro" }, { item: "Larino" }, { item: "Bojano" }, { item: "Agnone" }, { item: "Campomarino" }, { item: "Montenero di Bisaccia" }, { item: "Riccia" }, { item: "Guglionesi" },

  // Piemonte
  { item: "Torino" }, { item: "Novara" }, { item: "Alessandria" }, { item: "Asti" }, { item: "Cuneo" }, { item: "Vercelli" }, { item: "Biella" }, { item: "Verbania" }, { item: "Moncalieri" }, { item: "Collegno" }, { item: "Rivoli" }, { item: "Settimo Torinese" }, { item: "Grugliasco" }, { item: "Chieri" }, { item: "Pinerolo" }, { item: "Casale Monferrato" }, { item: "Novi Ligure" }, { item: "Tortona" }, { item: "Alba" }, { item: "Nichelino" }, { item: "Venaria Reale" }, { item: "Carmagnola" }, { item: "Ivrea" }, { item: "Fossano" }, { item: "Chivasso" }, { item: "Savigliano" }, { item: "Orbassano" }, { item: "Bra" }, { item: "Saluzzo" }, { item: "Acqui Terme" }, { item: "Mondovì" }, { item: "Domodossola" }, { item: "Borgomanero" }, { item: "Arona" }, { item: "Stresa" }, { item: "Bardonecchia" }, { item: "Sestriere" },

  // Puglia
  { item: "Bari" }, { item: "Taranto" }, { item: "Foggia" }, { item: "Lecce" }, { item: "Brindisi" }, { item: "Andria" }, { item: "Barletta" }, { item: "Trani" }, { item: "Cerignola" }, { item: "Altamura" }, { item: "Manfredonia" }, { item: "Molfetta" }, { item: "Bitonto" }, { item: "Monopoli" }, { item: "Corato" }, { item: "San Severo" }, { item: "Fasano" }, { item: "Lucera" }, { item: "Gallipoli" }, { item: "Ostuni" }, { item: "Gravina in Puglia" }, { item: "Martina Franca" }, { item: "Galatina" }, { item: "Francavilla Fontana" }, { item: "Nardò" }, { item: "Grottaglie" }, { item: "Bisceglie" }, { item: "Alberobello" }, { item: "Otranto" }, { item: "Vieste" }, { item: "Peschici" }, { item: "Polignano a Mare" }, { item: "Putignano" }, { item: "Locorotondo" }, { item: "Cisternino" },

  // Sardegna
  { item: "Cagliari" }, { item: "Sassari" }, { item: "Quartu Sant'Elena" }, { item: "Olbia" }, { item: "Alghero" }, { item: "Nuoro" }, { item: "Oristano" }, { item: "Carbonia" }, { item: "Iglesias" }, { item: "Selargius" }, { item: "Porto Torres" }, { item: "Monserrato" }, { item: "Arzachena" }, { item: "Sinnai" }, { item: "La Maddalena" }, { item: "Villacidro" }, { item: "Tempio Pausania" }, { item: "Tortolì" }, { item: "Ozieri" }, { item: "Assemini" }, { item: "Macomer" }, { item: "Siniscola" }, { item: "Dorgali" }, { item: "Carloforte" }, { item: "Pula" }, { item: "Bosa" }, { item: "San Teodoro" }, { item: "Orgosolo" }, { item: "Villasimius" }, { item: "Santa Teresa Gallura" }, { item: "Porto Cervo" },

  // Sicilia
  { item: "Palermo" }, { item: "Catania" }, { item: "Messina" }, { item: "Siracusa" }, { item: "Ragusa" }, { item: "Trapani" }, { item: "Caltanissetta" }, { item: "Agrigento" }, { item: "Enna" }, { item: "Marsala" }, { item: "Gela" }, { item: "Vittoria" }, { item: "Modica" }, { item: "Bagheria" }, { item: "Acireale" }, { item: "Mazara del Vallo" }, { item: "Paternò" }, { item: "Barcellona Pozzo di Gotto" }, { item: "Sciacca" }, { item: "Licata" }, { item: "Augusta" }, { item: "Avola" }, { item: "Caltagirone" }, { item: "Castelvetrano" }, { item: "Favara" }, { item: "Alcamo" }, { item: "Milazzo" }, { item: "Misterbianco" }, { item: "Adrano" }, { item: "Canicattì" }, { item: "Partinico" }, { item: "Termini Imerese" }, { item: "Erice" }, { item: "Taormina" }, { item: "Giarre" }, { item: "Comiso" }, { item: "Cefalù" }, { item: "Pozzallo" }, { item: "Noto" }, { item: "Pantelleria" }, { item: "Lampedusa" }, { item: "San Vito Lo Capo" }, { item: "Castellammare del Golfo" },

  // Toscana
  { item: "Firenze" }, { item: "Prato" }, { item: "Livorno" }, { item: "Arezzo" }, { item: "Pisa" }, { item: "Pistoia" }, { item: "Lucca" }, { item: "Grosseto" }, { item: "Massa" }, { item: "Carrara" }, { item: "Siena" }, { item: "Viareggio" }, { item: "Scandicci" }, { item: "Empoli" }, { item: "Campi Bisenzio" }, { item: "Sesto Fiorentino" }, { item: "Pontedera" }, { item: "Montecatini Terme" }, { item: "Piombino" }, { item: "Poggibonsi" }, { item: "Rosignano Marittimo" }, { item: "Cecina" }, { item: "Pietrasanta" }, { item: "Follonica" }, { item: "Forte dei Marmi" }, { item: "Portoferraio" }, { item: "Volterra" }, { item: "Castagneto Carducci" }, { item: "San Gimignano" }, { item: "Cortona" }, { item: "Montalcino" }, { item: "Pienza" }, { item: "Vinci" }, { item: "Montepulciano" }, { item: "Castiglione della Pescaia" }, { item: "Chianciano Terme" },

  // Trentino-Alto Adige
  { item: "Trento" }, { item: "Bolzano" }, { item: "Rovereto" }, { item: "Merano" }, { item: "Bressanone" }, { item: "Pergine Valsugana" }, { item: "Laives" }, { item: "Arco" }, { item: "Riva del Garda" }, { item: "Brunico" }, { item: "Appiano sulla Strada del Vino" }, { item: "Levico Terme" }, { item: "Ortisei" }, { item: "Vipiteno" }, { item: "Naturno" }, { item: "Castelrotto" }, { item: "Madonna di Campiglio" }, { item: "Canazei" }, { item: "Cavalese" }, { item: "Moena" }, { item: "Selva di Val Gardena" }, { item: "Dobbiaco" }, { item: "San Candido" }, { item: "Molveno" }, { item: "Andalo" }, { item: "Folgaria" },

  // Umbria
  { item: "Perugia" }, { item: "Terni" }, { item: "Foligno" }, { item: "Città di Castello" }, { item: "Spoleto" }, { item: "Orvieto" }, { item: "Bastia Umbra" }, { item: "Assisi" }, { item: "Gubbio" }, { item: "Corciano" }, { item: "Narni" }, { item: "Todi" }, { item: "Umbertide" }, { item: "Castiglione del Lago" }, { item: "Marsciano" }, { item: "Gualdo Tadino" }, { item: "Deruta" }, { item: "Norcia" }, { item: "Montefalco" }, { item: "Spello" }, { item: "Bevagna" }, { item: "Cascia" },

  // Valle d'Aosta
  { item: "Aosta" }, { item: "Châtillon" }, { item: "Saint-Vincent" }, { item: "Sarre" }, { item: "Courmayeur" }, { item: "Saint-Pierre" }, { item: "Gressan" }, { item: "Valtournenche" }, { item: "Breuil-Cervinia" }, { item: "Gressoney-Saint-Jean" }, { item: "Gressoney-La-Trinité" }, { item: "Cogne" }, { item: "Morgex" }, { item: "La Thuile" }, { item: "Pila" }, { item: "Champoluc" },

  // Veneto
  { item: "Venezia" }, { item: "Verona" }, { item: "Padova" }, { item: "Vicenza" }, { item: "Treviso" }, { item: "Rovigo" }, { item: "Belluno" }, { item: "Mestre" }, { item: "Bassano del Grappa" }, { item: "Chioggia" }, { item: "Castelfranco Veneto" }, { item: "Schio" }, { item: "Conegliano" }, { item: "Mira" }, { item: "San Donà di Piave" }, { item: "Villafranca di Verona" }, { item: "Montebelluna" }, { item: "Vittorio Veneto" }, { item: "Spinea" }, { item: "Jesolo" }, { item: "Mirano" }, { item: "Legnago" }, { item: "Arzignano" }, { item: "Portogruaro" }, { item: "Oderzo" }, { item: "Valdagno" }, { item: "Abano Terme" }, { item: "Thiene" }, { item: "Adria" }, { item: "Feltre" }, { item: "Caorle" }, { item: "Cortina d'Ampezzo" }, { item: "Bibione" }, { item: "Lazise" }, { item: "Peschiera del Garda" }, { item: "Malcesine" }, { item: "Asiago" }, { item: "Bardolino" }, { item: "Lido di Venezia" }
];



